### ISSUE TITLE
Cleaner doesn't work with None and actual ints

### ISSUE THREAD

**Issue by solomongifford** [jasonkeene/python-ubersmith#29]
I've been getting AttributeError("'int' object has no attribute 'replace'",) with certain device.list commands.

In the clean.py code below, if val is not a string, the replace fails.  If val is "None" it also fails.

<pre>
@cleaner
def int(val):
    return builtins.int(val.replace(',', ''))
</pre>
Solution:

<pre>
@cleaner
def int(val):
    if val is None:
        val = 0
    return builtins.int(str(val).replace(',', ''))
</pre>

This first ensures that None responses are 0 and secondly that val is converted to a string before executing the replace.

**Comment by jasonkeene** [comment]
Thanks for the report. I believe this was fixed as the cleaning behavior for int was changed.

https://github.com/jasonkeene/python-ubersmith/blob/882e7076bf972ae0894068427685bf67d3163711/ubersmith/clean.py#L47-L55
https://github.com/jasonkeene/python-ubersmith/blob/master/tests/test_cleaners.py#L141-L159

Although, it looks like we decided that if None is passed to a numeric cleaner it should return None.
