### ISSUE TITLE
Can you upload version 0.3.11 to pypi?

### ISSUE THREAD

**Issue by Kazanz** [jasonkeene/python-ubersmith#43]
Hey @jasonkeene, made an upgrade for Python3.5.  Tests are running.  I don't have permission to upload to pypi though.

Could you upload it or transfer ownership?  Thanks.

Hope all is well in CO :smile:

**Comment by theY4Kman** [comment]
What's your PyPI username? I'll add you as maintainer.

**Comment by jasonkeene** [comment]
@Kazanz shoot me an email if you still need access.

**Comment by theY4Kman** [comment]
I went ahead and uploaded 0.3.11 to PyPI today.

**Comment by jasonkeene** [comment]
![](https://media.giphy.com/media/vMnuZGHJfFSTe/giphy.gif)
