### ISSUE TITLE
create an outgoing ticket 

### ISSUE THREAD

**Issue by admin4ek** [jasonkeene/python-ubersmith#44]
Hello, 

Could you please give me some direction in order to resolve an issue with my script which should create an outgoing ticket..
I've tried to create a outgoing ticket via API. But I've got the following error:
**call**() takes exactly 1 argument (2 given)
Here is a part of the code in python:
        request = (recipient, subject, body, queue)
        support.ticket_submit_outgoing(request)
But I'm able to create a ticket(not outgoing) using the following code:
 return support.ticket_submit(body=body, subject=subject, email=recipient, name=author, queue=department)

Ubersmith version is 2.4.0
I'm using the from the module for python "support form ubersmith"
Thank you for your help

**Comment by theY4Kman** [comment]
If you're just looking for the solution to your problem, I'll begrudgingly
give it, but if you're looking to learn something, ponder this question:
Why does your submit_outgoing_ticket call differ from your submit_ticket
call?

**Comment by admin4ek** [comment]
Thank you for your reply.
 submit_outgoing_ticket call  should create an outgoing ticket to customer with email notification.
submit_ticket call should create just a ticket in UBER without email notification.

**Comment by theY4Kman** [comment]
The call should look like:

``` python
support.ticket_submit_outgoing(recipient=recipient, subject=subject, body=body, queue=queue)
```

If formatting is the reason you pulled the call args into a variable, use kwarg expansion with a dictionary, not a tuple:

``` python
request = {
    'recipient': recipient,
    'subject': subject,
    'body': body,
    'queue': queue,
}
support.ticket_submit_outgoing(**request)
```

Unlike other functions you may have used in Python, python-ubersmith's do not have positional arguments. This means you cannot simply pass in your args, like this: `call_func(a, b, c)`. Instead, you must explicitly name your arguments (known as keyword args): `call_func(a=a, b=b, c=c)`.

**Comment by theY4Kman** [comment]
There are other equivalent formats you may prefer, if you care how your code reads.

``` python
# One op, one line
support.ticket_submit_outgoing(recipient=recipient, subject=subject, body=body, queue=queue)

# One op, two lines (PEP8 compliance)
support.ticket_submit_outgoing(recipient=recipient, subject=subject, body=body,
                               queue=queue)

# One op, each kwarg on its own line
support.ticket_submit_outgoing(
    recipient=recipient, 
    subject=subject, 
    body=body,
    queue=queue,
)

# One op, two lines, dict expansion
support.ticket_submit_outgoing(**{'recipient': recipient, 'subject': subject, 
                                  'body': body, 'queue': queue})

# One op, dict expansion, dict pretty printed
support.ticket_submit_outgoing(**{
    'recipient': recipient,
    'subject': subject,
    'body': body, 
    'queue': queue,
})
```

Pick your poison.

**Comment by admin4ek** [comment]
Thank you so much. It is working fine for me.

**Comment by theY4Kman** [comment]
Glad to hear it. I'll close this for now. I hope your project goes well :)
